const empresasZF = [
  {
    "prioridad": "Alta",
    "empresa": "Abbott Medical Costa Rica",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Empresa de manufactura / procesadora",
    "ubicacion": "Alajuela / Coyol (validar)",
    "web": "https://www.abbott.com",
    "contacto": "Marco Obando – Manufacturing Director / Site Director / Plant Manager (perfil público LinkedIn)",
    "fuenteContacto": "https://www.linkedin.com/in/obandom",
    "notas": "Validar vigencia antes de contactar",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Boston Scientific de CR",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura avanzada + servicios globales / I+D",
    "ubicacion": "Heredia, Alajuela, Cartago",
    "web": "https://www.bostonscientific.com",
    "contacto": "John Kline – VP Operations; Mauricio Fabian – Logistics Manager; Diana Salas – Sr Material Planning Manager (perfiles públicos LinkedIn)",
    "fuenteContacto": "https://cr.linkedin.com/in/john-kline-ab125347",
    "notas": "Empresa de alta relevancia; múltiples sedes",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Edwards Lifesciences Costa Rica",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Procesadora / manufactura",
    "ubicacion": "Cartago (validar)",
    "web": "https://www.edwards.com",
    "contacto": "Pedro Castillo – Senior Manufacturing Manager; Gerardo Coto – VP & Plant General Manager (perfiles públicos LinkedIn)",
    "fuenteContacto": "https://cr.linkedin.com/in/pedro-castillo-437077167",
    "notas": "Validar cargo actual",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Baxter Productos Médicos",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura / productos médicos",
    "ubicacion": "Cartago (validar)",
    "web": "https://www.baxter.com",
    "contacto": "Laura Quesada Lizano – Plant General Manager hasta abr-2025; Vinny Marchionni – Plant Manager (perfil público LinkedIn)",
    "fuenteContacto": "https://cr.linkedin.com/in/laura-quesada-lizano",
    "notas": "Validar vigencia; puede no estar actual",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Componentes INTEL de CR",
    "sector": "Tecnología / manufactura avanzada",
    "actividad": "Procesadora / componentes electrónicos",
    "ubicacion": "Heredia / Belén (validar)",
    "web": "https://www.intel.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.intel.com/content/www/us/en/jobs/locations/costa-rica.html",
    "notas": "Contacto sugerido: Site Operations / Plant Manager",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Johnson & Johnson MedTech CR Limitada",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Procesadora inciso f)",
    "ubicacion": "Coyol / Alajuela (validar)",
    "web": "https://www.jnjmedtech.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.jnj.com",
    "notas": "Contacto sugerido: Operations Manager / Manufacturing Director",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Coopervision Manufacturing CR",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura",
    "ubicacion": "Alajuela / Coyol (validar)",
    "web": "https://www.coopervision.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.coopervision.com",
    "notas": "Contacto sugerido: Plant Manager / Supply Chain Manager",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Coloplast Volume Manufacturing CR",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura",
    "ubicacion": "Cartago (validar)",
    "web": "https://www.coloplast.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.coloplast.com",
    "notas": "Contacto sugerido: Operations Manager",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Freudenberg Medical",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura",
    "ubicacion": "Alajuela / Coyol (validar)",
    "web": "https://www.freudenbergmedical.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.freudenbergmedical.com",
    "notas": "Contacto sugerido: Plant Manager / Operations Director",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Penumbra Costa Rica S.R.L.",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Ciencias de la vida",
    "ubicacion": "Coyol / Alajuela (validar)",
    "web": "https://www.penumbrainc.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.penumbrainc.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Inari Medical Costa Rica SRL",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura y procesadora",
    "ubicacion": "Coyol / Alajuela (validar)",
    "web": "https://www.inarimedical.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.inarimedical.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Terumo Cardiovascular Costa Rica",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura",
    "ubicacion": "La Aurora / Heredia (validar)",
    "web": "https://www.terumo.com",
    "contacto": "Alexander Unfried – Plant Manager / General Manager (perfil público LinkedIn)",
    "fuenteContacto": "https://cr.linkedin.com/in/alexander-unfried-b3a55922",
    "notas": "Empresa no visible en el corte principal AZOFRAS, incluida por relevancia sectorial",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Bayer Medical S.R.L.",
    "sector": "Ciencias de la vida / farmacéutica-dispositivos",
    "actividad": "Manufactura / procesadora",
    "ubicacion": "Heredia (validar)",
    "web": "https://www.bayer.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.bayer.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Allergan CR",
    "sector": "Ciencias de la vida / farmacéutica-dispositivos",
    "actividad": "Manufactura / servicios",
    "ubicacion": "Heredia / Alajuela (validar)",
    "web": "https://www.abbvie.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.abbvie.com",
    "notas": "Allergan es parte de AbbVie",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Admedes S.A. (G. Rau Group)",
    "sector": "Ciencias de la vida / componentes médicos",
    "actividad": "Manufactura",
    "ubicacion": "Cartago (validar)",
    "web": "https://www.admedes.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.admedes.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Biomerics ATL",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura",
    "ubicacion": "Alajuela (validar)",
    "web": "https://www.biomerics.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.biomerics.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "CSI Closure Systems Manufacturing de Centro América",
    "sector": "Manufactura avanzada / empaques",
    "actividad": "Manufactura",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.csiclosures.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.csiclosures.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "DEROYAL Científica de Latinoamérica",
    "sector": "Ciencias de la vida / dispositivos médicos",
    "actividad": "Manufactura / procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.deroyal.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.deroyal.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Precision Concepts Costa Rica",
    "sector": "Ciencias de la vida / manufactura avanzada",
    "actividad": "Empresa de servicios y procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.pciplastics.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.pciplastics.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Kellington Laboratories S.A.",
    "sector": "Ciencias de la vida / laboratorio",
    "actividad": "Procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Samtec Interconnect Assembly SIA Costa Rica S.R.L.",
    "sector": "Electrónica / manufactura avanzada",
    "actividad": "Comercial exportación, servicios y procesadora inciso f)",
    "ubicacion": "Alajuela (validar)",
    "web": "https://www.samtec.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.samtec.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Flextronics de Costa Rica",
    "sector": "Manufactura avanzada / electrónica",
    "actividad": "Manufactura / servicios",
    "ubicacion": "Alajuela (validar)",
    "web": "https://www.flex.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.flex.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Alta",
    "empresa": "Proquinal Costa Rica",
    "sector": "Manufactura avanzada / materiales",
    "actividad": "Comercial exportación, servicios y procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.proquinal.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.proquinal.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Amazon Support Services CR",
    "sector": "Servicios compartidos / tecnología",
    "actividad": "Servicios",
    "ubicacion": "San José / Heredia (validar)",
    "web": "https://www.amazon.jobs",
    "contacto": "No aplica Plant Manager; contacto sugerido: Site Leader / Operations Manager",
    "fuenteContacto": "https://www.amazon.jobs",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Accenture",
    "sector": "Servicios / tecnología / consultoría",
    "actividad": "Servicios",
    "ubicacion": "San José / Heredia (validar)",
    "web": "https://www.accenture.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Country Manager / Operations Lead",
    "fuenteContacto": "https://www.accenture.com/cr-es",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Cognizant Technology Solutions de Costa Rica",
    "sector": "Servicios / tecnología",
    "actividad": "Servicios",
    "ubicacion": "San José / Heredia (validar)",
    "web": "https://www.cognizant.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Delivery Center Head / Operations Lead",
    "fuenteContacto": "https://www.cognizant.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Roche Servicios",
    "sector": "Servicios compartidos / ciencias de la vida",
    "actividad": "Comercial exportación y servicios",
    "ubicacion": "San José / Heredia (validar)",
    "web": "https://www.roche.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Site Lead / Shared Services Director",
    "fuenteContacto": "https://www.roche.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Cargill Business Services",
    "sector": "Servicios compartidos",
    "actividad": "Servicios",
    "ubicacion": "Heredia (validar)",
    "web": "https://www.cargill.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Shared Services / Operations Lead",
    "fuenteContacto": "https://www.cargill.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "DHL Global Forwarding Costa Rica",
    "sector": "Logística / freight forwarding",
    "actividad": "Empresa de servicios",
    "ubicacion": "San José / Alajuela (validar)",
    "web": "https://www.dhl.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Station Manager / Country Manager",
    "fuenteContacto": "https://www.dhl.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Baxter America Services",
    "sector": "Servicios compartidos / ciencias de la vida",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.baxter.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Shared Services Leader",
    "fuenteContacto": "https://www.baxter.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Bacardi Soluciones",
    "sector": "Servicios compartidos",
    "actividad": "Servicios",
    "ubicacion": "Escazú / San José (validar)",
    "web": "https://www.bacardilimited.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Shared Services Manager",
    "fuenteContacto": "https://www.bacardilimited.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "BAC Latam",
    "sector": "Servicios financieros / back office",
    "actividad": "Servicios",
    "ubicacion": "San José (validar)",
    "web": "https://www.baccredomatic.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "https://www.baccredomatic.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "BCD Travel Americas Operations Center",
    "sector": "Servicios / viajes corporativos",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.bcdtravel.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Center Manager",
    "fuenteContacto": "https://www.bcdtravel.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Bill Gosling Outsourcing S.R.L.",
    "sector": "Servicios / BPO",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.billgosling.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Director",
    "fuenteContacto": "https://www.billgosling.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Boston Consulting Group",
    "sector": "Servicios profesionales",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.bcg.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Office Lead / Operations",
    "fuenteContacto": "https://www.bcg.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Centro de Servicios Compartidos Bimbo",
    "sector": "Servicios compartidos",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.grupobimbo.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Shared Services Manager",
    "fuenteContacto": "https://www.grupobimbo.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "DOLE Shared Services",
    "sector": "Servicios compartidos / agroindustria",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.dole.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Shared Services Manager",
    "fuenteContacto": "https://www.dole.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Emerson Electric CR",
    "sector": "Servicios / ingeniería / tecnología",
    "actividad": "Servicios / manufactura avanzada",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.emerson.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.emerson.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Foundever Costa Rica",
    "sector": "Servicios / BPO",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://foundever.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Director",
    "fuenteContacto": "https://foundever.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Gensler Costa Rica",
    "sector": "Servicios profesionales / arquitectura",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.gensler.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Studio Director / Office Leader",
    "fuenteContacto": "https://www.gensler.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Goodyear Costa Rica S.R.L.",
    "sector": "Servicios / manufactura",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.goodyear.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.goodyear.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Tebra Technologies S.A.",
    "sector": "Servicios / tecnología",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.tebra.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Site Lead / Operations",
    "fuenteContacto": "https://www.tebra.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Jones Lang LaSalle",
    "sector": "Servicios inmobiliarios / facilities",
    "actividad": "Comercial exportación y servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.jll.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Facilities / Account Manager",
    "fuenteContacto": "https://www.jll.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Prime Logistics (GAG) S.A.",
    "sector": "Logística",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "GFI Pharma Logistics",
    "sector": "Logística farmacéutica",
    "actividad": "Servicios / logística",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Coca Cola Industrias",
    "sector": "Manufactura / bebidas",
    "actividad": "Procesadora / servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.coca-colacompany.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.coca-colacompany.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Bridgestone de Costa Rica, S.A. (B.A.T.O)",
    "sector": "Manufactura / llantas / servicios",
    "actividad": "Empresa de servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.bridgestoneamericas.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.bridgestoneamericas.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Firestone Industrial Products",
    "sector": "Manufactura / industrial",
    "actividad": "Manufactura",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.firestoneip.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.firestoneip.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Rawlings de Costa Rica",
    "sector": "Manufactura / artículos deportivos",
    "actividad": "Comercial exportación, servicios y procesadora inciso f)",
    "ubicacion": "Turrialba / Costa Rica (validar)",
    "web": "https://www.rawlings.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.rawlings.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Hitrónicos de Costa Rica",
    "sector": "Manufactura / electrónica",
    "actividad": "Procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Casa Proveedora Phillips S.A",
    "sector": "Manufactura / distribución",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Alimentos Pro Salud",
    "sector": "Manufactura / alimentos",
    "actividad": "Procesadora / alimentaria",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia de Planta / Operaciones",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Biomar Aquacorporation Products",
    "sector": "Manufactura / alimentos acuícolas",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.biomar.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.biomar.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Compañía Industrial Aceitera Coto 54",
    "sector": "Manufactura / agroindustria",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Congelados y Jugos del Valle Verde",
    "sector": "Manufactura / alimentos",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Fructa CR",
    "sector": "Manufactura / alimentos",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Media",
    "empresa": "Fruta Sana FSL",
    "sector": "Manufactura / alimentos",
    "actividad": "Procesadora",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Administradora de Parque Génesis",
    "sector": "Administradora de parque",
    "actividad": "Administradora de parques",
    "ubicacion": "Heredia / San José (validar)",
    "web": "https://www.parquegenesis.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia General / Comercial",
    "fuenteContacto": "https://www.parquegenesis.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Centro de Ciencia y Tecnología Ultrapark",
    "sector": "Administradora de parque / real estate",
    "actividad": "Administradora / servicios",
    "ubicacion": "Heredia (validar)",
    "web": "https://www.ultrapark.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Property / Operations Manager",
    "fuenteContacto": "https://www.ultrapark.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "CF Free Zone Park",
    "sector": "Administradora de parque",
    "actividad": "Administradora de parques",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Norte Free Zone Park S.R.L.",
    "sector": "Administradora de parque",
    "actividad": "Administradora de parques",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Ultrapark LAG, S.A.",
    "sector": "Administradora de parque / real estate",
    "actividad": "Servicios",
    "ubicacion": "Heredia (validar)",
    "web": "https://www.ultrapark.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations / Property Manager",
    "fuenteContacto": "https://www.ultrapark.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Ultrapark Dos, S.A.",
    "sector": "Administradora de parque / real estate",
    "actividad": "Servicios",
    "ubicacion": "Heredia (validar)",
    "web": "https://www.ultrapark.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations / Property Manager",
    "fuenteContacto": "https://www.ultrapark.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Eurocenter Inmobiliaria de Costa Rica ECR",
    "sector": "Real estate / parque empresarial",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Property Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Everty Icon Tower EIT Limitada",
    "sector": "Real estate / parque empresarial",
    "actividad": "Empresa de servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.everty.com",
    "contacto": "No aplica Plant Manager; contacto sugerido: Property / Operations Manager",
    "fuenteContacto": "https://www.everty.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Innovapark S.A.",
    "sector": "Administradora de parque",
    "actividad": "Administradora de parques",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Inco Corporate Center, S.A.",
    "sector": "Real estate / servicios",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Inversiones Inmobiliarias Bonavista (IIBV)",
    "sector": "Real estate / servicios",
    "actividad": "Empresa de servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Property Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "BATCCA Park Inversiones Inmobiliarias, S.A.",
    "sector": "Real estate / servicios",
    "actividad": "Administradora / inmobiliaria",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Condominio Parque Industrial Zona Franca Alajuela",
    "sector": "Administradora de parque",
    "actividad": "Administradora de parques",
    "ubicacion": "Alajuela",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Gerencia del parque",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Circuito Sociedad Anónima",
    "sector": "Manufactura / servicios",
    "actividad": "No especificado en corte inicial",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Compact Seeds & Clones",
    "sector": "Agrotech / semillas",
    "actividad": "No especificado en corte inicial",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Compañía Anónima Distribuidora Farmacéutica Cadifar S.A. (CADIFAR)",
    "sector": "Distribución farmacéutica",
    "actividad": "Comercial exportación y servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Cooperativa Autogestionaria de Servicios Aeroindustriales",
    "sector": "Servicios aeroindustriales",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Costa Rica Lifting Services S.A.",
    "sector": "Servicios industriales",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Etiquetas Impresas ETIPRES",
    "sector": "Manufactura / etiquetas",
    "actividad": "Procesadora / manufactura",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "FL Pallets",
    "sector": "Manufactura / embalaje",
    "actividad": "Procesadora / servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Gener Eigth LLC S.R.L.",
    "sector": "Servicios / procesadora",
    "actividad": "Servicios y procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Novashore Outsourcing Solutions S.A.",
    "sector": "Servicios / outsourcing",
    "actividad": "Contacto público AZOFRAS: info@crnova.com",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "mailto:info@crnova.com",
    "notas": "AZOFRAS muestra info@crnova.com",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Soportexperto.com S.A",
    "sector": "Servicios / soporte",
    "actividad": "Servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No aplica Plant Manager; contacto sugerido: Operations Manager",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "Matthews International Corporation Costa Rica SRL",
    "sector": "Manufactura / servicios",
    "actividad": "Procesadora inciso f)",
    "ubicacion": "Costa Rica (validar)",
    "web": "https://www.matw.com",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "https://www.matw.com",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  },
  {
    "prioridad": "Baja",
    "empresa": "PSCR Exportadora Sociedad Anónima",
    "sector": "Servicios / exportación",
    "actividad": "Comercial exportación y servicios",
    "ubicacion": "Costa Rica (validar)",
    "web": "",
    "contacto": "No identificado públicamente en esta revisión",
    "fuenteContacto": "",
    "notas": "",
    "fuenteBase": "https://www.azofras.com/empresas-zonas-francas/"
  }
];
